name: Documentation

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'arbi/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build-deploy-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        run: |
          rustup toolchain install nightly
          rustup override set nightly
          
      - name: Build Documentation
        run: |
          RUSTDOCFLAGS="--html-in-header ./arbi/doc/header.html --cfg docsrs" cargo +nightly doc --no-deps --all-features
          
      - name: Prepare PR-specific path
        if: github.event_name == 'pull_request'
        run: |
          mkdir -p "pr-${{ github.event.number }}"
          mv target/doc "pr-${{ github.event.number }}/doc"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Comment PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const url = `${{ steps.deployment.outputs.page_url }}pr-${{ github.event.number }}/doc/arbi/index.html`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              issue_number: context.payload.pull_request.number,
              body: `📚 Documentation preview is ready!\nView it here: ${url}`
            });
