name: Static Analysis

on:
  push:
    branches: [ main ]
    paths:
      - 'arbi/**'
      - 'examples/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'arbi/**'
      - 'examples/**'
  workflow_dispatch:

jobs:
  rust-stable-clippy-fmt-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        rustup update stable && rustup override set stable
        rustup component add clippy rustfmt
        cargo install cargo-audit
    - run: cargo clippy --features "std,rand" -- -D warnings
    - run: |
        rustup toolchain install nightly
        cargo +nightly fmt -- --check
    - run: cargo audit

  rust-1point65-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        rustup toolchain install 1.65.0 && rustup override set 1.65.0
        rustup component add clippy
    - run: cargo clippy --features "std,rand" -- -D warnings
