name: Static Analysis

on:
  push:
    branches: [ main ]
    paths:
      - 'arbi/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'arbi/**'
  workflow_dispatch:

jobs:
  rust-stable-clippy-audit-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup update stable && rustup override set stable
    - run: cargo clippy --features "std,rand" -- -D warnings
    - run: |
        cargo install cargo-audit
        cargo audit
    - name: rustfmt (nightly)
      run: |
        rustup toolchain install nightly
        rustup component add rustfmt --toolchain nightly
        cargo +nightly fmt -- --check

  rust-1point65-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        rustup toolchain install 1.65.0 && rustup override set 1.65.0
        rustup component add clippy
    - run: cargo clippy --features "std,rand" -- -D warnings
