name: Test

on:
  push:
    branches: [ main ]
    paths:
      - 'arbi/**'
      - 'examples/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'arbi/**'
      - 'examples/**'

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      shell: bash

    - name: Run tests
      run: |
        cargo test --release

        # # Run examples
        # for example in examples/*; do
        #   if [ -f "$example/Cargo.toml" ]; then
        #     cargo run --release --manifest-path "$example/Cargo.toml"
        #   fi
        # done
      shell: bash

  # Test MSRV
  build-and-test-rust-1point61:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust 1.65
      run: |
        rustup toolchain install 1.65.0
        rustup default 1.65.0
      shell: bash

    - name: Run tests with Rust 1.65
      run: |
        cargo test --release
      shell: bash
